vich_uploader:
    db_driver: orm
    mappings:
        path_file:
            uri_prefix: /images/path
            upload_destination: '%upload_directory_path%'
        club_file:
            uri_prefix: /images/club
            upload_destination: '%upload_directory_club%'
        equipment_file:
            uri_prefix: /images/equipment
            upload_destination: '%upload_directory_equipment%'
        discipline_file:
            uri_prefix: /images/discipline
            upload_destination: '%upload_directory_discipline%'
        brand_file:
            uri_prefix: /images/brand
            upload_destination: '%upload_directory_brand%'
        home_file:
            uri_prefix: /images/home
            upload_destination: '%upload_directory_home%'
